# Generated by Django 5.0.6 on 2024-12-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('congestion_level', models.FloatField(default=0.0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('video_source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('trajectory', models.JSONField()),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
                ('traffic_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_app.trafficdata')),
            ],
        ),
    ]
