# Generated by Django 5.1.4 on 2025-04-22 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0003_alter_trafficdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity', models.IntegerField(choices=[(1, 'Mineur'), (2, 'Modéré'), (3, 'Sévère')], default=1)),
                ('details', models.JSONField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('false_positive', models.BooleanField(blank=True, null=True)),
                ('contributing_factors', models.JSONField(blank=True, null=True)),
                ('traffic_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='traffic_app.trafficdata')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
