# Generated by Django 5.1.4 on 2025-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0004_accident'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
