# Generated by Django 5.2.1 on 2025-05-12 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0005_vehicle_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('accident', 'Accident'), ('roadwork', 'Travaux'), ('police', 'Présence Police')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('severity', models.IntegerField(choices=[(1, 'Faible'), (2, 'Modéré'), (3, 'Sévère')], default=1)),
                ('description', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('notified', models.BooleanField(default=False)),
                ('traffic_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_app.trafficdata')),
            ],
        ),
    ]
